apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:EGBs27pWuZRN,iv:YrienzjWsX9gCTcZDpGvNlQJCjl/01GvHM4glTck9qo=,tag:W9XhIWG7PwoCDxPoHkvuVQ==,type:str]
sops:
  age:
    - recipient: age13fsn02sppxwtgaj3ecmyu8jummt60fcp3js6h8ja0hj0qltr3a5sm7eadl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSis1Z2ZKUE5tUXkxZDFI
        SzhRK3N5Qkc4czcrK3VlS0lEejg5a29mcWlFCkRiSHEwT1c5Tnh4aVUzazgrcXJk
        dXhCYWIwd09uN0JQdFpjNmpNSVB3MnMKLS0tIFVVWXdNL0liTERCZWtlNFdMQng4
        YnV6THA1NzlxbGg0SjhyYUEyblRhUkUKmfoboS49Offr6XcIQqixVP4vG8tWq5Mk
        gN3SF18BDNu8UPLumIFyHAG5+4IRKIkVXIxp5+w0eJMRlRKqMOfWow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-05T23:09:32Z"
  mac: ENC[AES256_GCM,data:xBtVdNZhBcUkQqngFynzavRTFl1g2O/q7X2U1yJnkSBbVYi+TncSkHUm1gMjJyBBLur91E03Rtelsjw05vjbmi3R2huVFnXkocdCIywFGmPvPLnT4y4u3DbLZ1cxOHJ3s2fPV2dwuBJH5ZOGxl1025OnVSSXo2ajhq9l73lW/fc=,iv:KfhXh7sqj/EJbFH5V2um2u6g5QC268pmkwoLe6nB1rw=,tag:aoAA8a9D7J7WoFO4Su1okg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
